# Generated by Django 5.1.2 on 2024-10-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
