# Generated by Django 5.1.2 on 2024-10-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_autoreply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autoreply",
            name="reply_content_template",
        ),
    ]
