services:
  db:
    image: "postgres:17"
    container_name: db
    ports:
      - "5400:5432"
    env_file:
      - ./.env
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: "redis:7"
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - app_network
    restart: always

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - app_network
    restart: always

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A post_manager worker --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - ./.env
    networks:
      - app_network
    restart: always

volumes:
  pgdata:
    driver: local

networks:
  app_network:
    driver: bridge
